### PR TITLE
Update impls.html

### PR DESCRIPTION
**Pull request by rumpelsepp**
Add https://github.com/fxamacker/cbor and remove incomplete implementation

### CODE REVIEW

**Comment by cabo** [comment]
So what is the state of 2tvenom's implementation?

**Comment by rumpelsepp** [comment]
According to github, it seems unmaintained for the last 2 years and has at least these known issues (from the readme):
 
* Not support tags. 6 major type (in future)
* Not support 16 floats encoding
* Not decode nil (null) vars
* Encode does't support indefinite-length values.

**Comment by cabo** [comment]
> According to github, it seems unmaintained for the last 2 years 

Yes, I saw that.  Is the other implementation you are referencing compatible (at least vaguely)?
Or are the completely unrelated?

> and has at least these known issues (from the readme):
> 
> * Not support tags. 6 major type (in future)

Neither does the fxamacker one, AFACS.

> * Not support 16 floats encoding

OK

> * Not decode nil (null) vars

That is a limitation.

> * Encode does't support indefinite-length values.

Does the fxamacker one?


Just trying to find out if the 2tvenom one should stay in or is wholeheartedly replaced.  Maybe I should contact 2tvenom.

**Comment by rumpelsepp** [comment]
> Yes, I saw that. Is the other implementation you are referencing compatible (at least vaguely)?

Would say so. Same API design.

**Comment by fxamacker** [comment]
Hi,

I maintain [fxamacker/cbor](https://github.com/fxamacker/cbor).  Thanks for considering it.

> Not support tags. 6 major type

My decoder ignores tags but decodes tagged data.  Encoder does not support tags yet.  

> Encode does't support indefinite-length values.

My decoder supports indefinite-length values for bytes/strings/arrays/maps.  Encoder doesn't support it yet.  

By comparison, 2tvenom/cbor doesn't appear to support decoding indefinite-length values, based on a quick look at [2tvenom/cbor/cbor.go](https://github.com/2tvenom/cbor/blob/384e799bd841fc59220d0f5911b8cbde7b380875/cbor.go#L152).

Thanks again,

Faye

**Comment by rumpelsepp** [comment]
>> Encode does't support indefinite-length values.
>
> Does the fxamacker one?

Since the last release it does.

https://github.com/fxamacker/cbor/releases/tag/v0.2.0

**Comment by rumpelsepp** [comment]
@cabo Do you expect me to change this pull request in any way? I am happy to incorporate any feedback.

**Comment by fxamacker** [comment]
I released [fxamacker/cbor](https://github.com/fxamacker/cbor) v1.0.  Changes are summarized [here](https://github.com/fxamacker/cbor/releases).

Please let me know if you have any questions or suggestions.  Thanks.

**Comment by rumpelsepp** [comment]
@cabo The mentioned cbor implementation evolved rapidly and is now in a state that I recommend adding to the website. The README now covers information to all limitations and there is a roadmap as well.

**Comment by x448** [comment]
@cabo Slideshow contains comparisons to a CBOR implementation on cbor.io that doesn't offer preferred serialization (ints and floats to their shortest form when values can round-trip):

[CBOR Library - Slideshow and Latest Docs.](https://github.com/fxamacker/cbor/blob/master/README.md)

fxamacker/cbor v1.5 adds support for encoding to float16 (IEEE 754 binary16) for preferred serialization.  EncOptions for floating-point include:
* __ShortestFloat__:  ShortestFloatNone, ShortestFloat16
* __InfConvert__:  InfConvertNone, InfConvertFloat16
* __NaNConvert__:  NaNConvertNone, NaNConvert7e00, NaNConvertQuiet, NaNConvertPreserveSignal

Predefined EncOptions are returned by functions so users don't have to know details:
* CanonicalEncOptions()
* CTAP2EncOptions()
* CoreDetEncOptions()
* PreferredUnsortedEncOptions()

Custom EncOptions can be made by changing individual settings to match a protocol.

__Status__
 * Code coverage is the highest for any CBOR library in Go I've seen. And all 375+ tests pass.
 * v1.4 passed 4+ billion execs during coverage-guided fuzzing using 1000+ CBOR files (18 days after release).  Fuzzing for v1.5 reached 250+ million and is in progress.

__Roadmap__
 * Support for CBOR tags (major type 6) is in progress and will be in the next 1 or 2 release.
 * Support for handling duplicate map keys is also planned.

**Comment by fxamacker** [comment]
@cabo Hello!  I released [fxamacker/cbor](https://github.com/fxamacker/cbor) 2.1.  It is a fast, safe, and full-featured generic CBOR encoder and decoder in Go.

Compared to the best Go impl listed on cbor.io, it is more full-featured, faster, uses less memory, produces smaller data, and produces smaller apps (see comparisons below).

Please let me know if there's anything that's preventing fxamacker/cbor from being listed.  I can provide a PR if you prefer not to replace an existing Go impl.  Thanks!

fxamacker/cbor 2.1 supports:
* __CBOR tags__ (API supports built-in and user-defined tags).
* __Preferred serialization__, including IEEE 754 binary16.
* __Duplicate map key detection__ (option to enforce or ignore).
* __Indefinite length data__ for encoding and decoding.
* Sort options: unsorted, length-first and bytewise-lexicographic.
* Encoder options for floating-point shortest form, NaN, and Infinity.
* Decoder checks for well-formedness and validates data.
* Decoder doesn't crash and avoids resource exhaustion from malformed/malicious CBOR data.

More info at: [Encoder and Decoder Options](https://github.com/fxamacker/cbor#options), and [Standards](https://github.com/fxamacker/cbor#standards)

Here's how fxamacker/cbor compares to the best Go library currently listed on cbor.io using using test data from RFC 8392 A.1 for speed and memory comparisons.

__Safety Comparison__
|                   | fxamacker/cbor 2.1               |ugorji/go 1.1.7                   |
|-------------------|----------------------------------|----------------------------------|
|Bad data 1  | 57.4 ns/op, 32 B/op, 1 allocs/op |⚠️ fatal error: out of memory
|Bad data 2  | 67.7 ns/op, 32 B/op, 1 allocs/op |⚠️ runtime: out of memory: cannot allocate

__Compiled Program Size Comparison__
|                   | fxamacker/cbor 2.1               |ugorji/go 1.1.7                   |
|-------------------|----------------------------------|----------------------------------|
|Custom app  | 2.7 MB | 11.9 MB
|cisco/senml  | 7.6 MB | 12 MB

__Speed Comparison (lower ns/op is better)__
|                   | fxamacker/cbor 2.1          |ugorji/go 1.1.7                   |
|-------------------|-----------------------------|----------------------------------|
|Encode CWT  | 457 ns/op | 995 ns/op
|Decode CWT  | 796 ns/op | 1105 ns/op

__Memory Comparison (lower numbers are better)__
|                   | fxamacker/cbor 2.1          |ugorji/go 1.1.7                   |
|-------------------|-----------------------------|----------------------------------|
|Encode CWT  | 176 B/op, 2 allocs/op | 1424 B/op, 4 allocs/op
|Decode CWT  | 176 B/op, 6 allocs/op | 568 B/op, 6 allocs/op

**Comment by cabo** [comment]
Thank you for this interesting implementation, and apologies for my glacial speed merging the pointer to this.

**Pull request merged**
